### ISSUE TITLE
Relationship editor: Max Occurs line disappears when extra metadata pair is added

### ISSUE THREAD

**Issue by charlescrichton** [MetadataRegistry/ModelCataloguePlugin#498]
To replicate:

1. Go to data element that does not have relationship metadata values ("`Min Occurs`" and "`Max Occurs`") set.
2. Click "`Edit`".
3. Click lower "`+`" to add an extra metadata value pair.
4. Enter name and value - for example "`Barcode Standard`" and "`GS1`".
5. Click on "`Update Relationship`".
    *Have a look at the metadata associated with the  data element at this point*

6. Now click on "`Edit`" again.

**Problem: Now the "`Max Occurs`" line seems to have disappeared.**

**Comment by davidmilward** [comment]
no longer occurs on latest codebase
